export const strings = {
  explainer: {
    addMarkerToolTitle: "Add Boundary Markers mode",
    addMarkerTool: "In this mode, tap the map to add a new boundary marker at that location. New markers will be added along the active edge.",
    boundaryMarkerTitle: "Boundary Markers",
    boundaryMarker: "Press and hold the icons to move the boundary markers.",
    boundaryToolTitle: "Change Active Edge mode",
    boundaryTool: "In this mode, tap a boundary edge to activate it. New boundary markers will be inserted along the active edge (which is red and has spaces).",
    changeUnitsTitle: "Change units",
    changeUnits: "Tap the course length to change the displayed units.",
    controlActiveTitle: "Next Control",
    controlActive:"The next control to visit is in red.",
    controlFinishTitle: "Finish",
    controlFinish:"After visiting all numbered controls, go to the double-circle to finish!",
    controlRegularTitle: "Numbered controls",
    controlRegularStandard:"Travel to the numbered controls in order for a Standard course.",
    controlRegularScoreO:"Travel to the numbered controls in ANY order for a Score-O course.",
    controlStartTitle: "Start",
    controlStart: "Travel to the triangle to start.",
    controlVisitedTitle: "Visited controls",
    controlVisited: "Visited controls turn grey.",
    deleteToolTitle: "Delete Boundary Markers mode",
    deleteTool: "In this mode, tap a boundary marker to remove it.",
    gpsHintTitle: "Show my location",
    gpsHint:"Tap to get a hint by showing your location on the map.",
    layerTitle: "Cycle through map layers",
    layer: "Tap to change between satellite, hybrid, terrain, map, and orienteering views.",
    moveControlTitle: "Numbered control",
    moveControl: "Press and hold a circle to move a control.",
    moveFinishTitle: "Finish control",
    moveFinish: "Press and hold the double-circle to drag the Finish to a different location.",
    setFinishTitle: "Finish control",
    setFinish: "Tap anywhere on the map to place the Finish there, or press and hold the double-circle to drag the Finish to a different location.",
    moveStartTitle: "Start control",
    moveStart: "Press and hold the triangle to drag the Start to a different location.",
    setStartTitle: "Start control",
    setStart: "Tap anywhere on the map to place the Start there, or press and hold the triangle to drag the Start to a different location.",
    QRIconTitle: "Share Course via QR Code",
    QRIcon: "Tap to share the course with another person via QR code.  They will need to tap 'Import Via QR' from the “Course Type” page of their Dice-O app.",
    randomToolTitle: "Roll the Orienteering Die!",
    randomTool: "Tap the die to make a new random orienteering course!",
    skipTitle: "Skip next control",
    skip:"Tap to skip over the next control.",
    settingsTitle: "Settings",
    settings:"Tap to view the settings page.",
    finishNowTitle: "Finish Now",
    finishNow:"Tap to end the course now, without finding the rest of the controls.",
  },
  header: {
    about: "About",
    back: "Back",
    courseType: "Course Type",
    disclaimer: "Disclaimer",
    exportQR: 'Share this Course',
    controlLogged: "Control Logged", //TODO differentiate between skipped and found controls
    game: 'Event in Progress',
    gameExit: 'Exit',
    gameExplainer: 'Completing a Course',
    gameSettings: "Settings",
    home: "Home",
    importQR: 'Import a Course',
    results: "Results",
    setBoundary: "Set Course Boundary",
    setBoundaryExplainer: 'Setting the Boundary',
    setBoundaryShort: "Boundary",
    setCourse: "Set the Course",
    setCourseExplainer: 'Setting the Course',
    setFinish: 'Tap to move the Finish',
    setFinishExplainer: 'Setting the Finish',
    setFinishShort: 'Finish',
    setStart: 'Tap to move the Start',
    setStartExplainer: 'Setting the Start',
    setStartShort: 'Start',
    settings: "Settings",
    settingsAdvanced: "Advanced Settings",
    settingsShort: "Settings",
  },
  about: {
    p1: "Dice-O is an app for practicing orienteering.",
    p2: "Orienteering is a sport where you navigate to locations shown on a map (called “control points”) through varied terrain, as fast as you can. You can also ignore the racing element, and participate as a leisure activity that encourages exploring new places or routes between them, while getting exercise.",
    p3: "Dice-O helps you quickly and randomly generate orienteering-style courses. To set up a course you will:",
    bullet1: "• Define the course boundary.  All controls will be placed inside the boundary.",
    bullet2: "• Set a starting location for the course",
    bullet3: "• Set an ending location for the course",
    bullet4: "• Randomly generate the control points between the start and end",
    p4: "After setting up a course, you are ready to go orienteering!",
    wikipediaLinkPre: "You can learn more about the sport of orienteering on ",
    wikipediaLinkText: "Wikipedia",
    wikipediaLinkURL: "https://en.wikipedia.org/wiki/Orienteering",
    wikipediaLinkPost: ".",
    CTA: "Continue",
  },
  disclaimer: {
    p1: "Dice-O is not a replacement for orienteering courses set by orienteering professionals, which are complex to set well.",
    p2: "Map data in the app is sourced from Google Maps, and is not nearly as detailed as good orienteering maps. This app is best used in an area that you already know well, or in conjunction with a real orienteering map.",
    p3: "The app only uses your devices foreground location permissions.  You will not be able to check into control points while your device is off, or while the app is minimized.",
    p4: "Dice-O may place controls anywhere inside of the boundary you define, without respect to bodies of water, private property, roadways, train tracks, etc.  Always review the location of every control point before embarking on any course, and adjust any that are inacessible or inappropriate.",
    p5: "Please use common sense while using Dice-O. Do not trespass. Do not use Dice-O while operating a motor vehicle. Do not do anything dangerous while using this app. The creator of this app is not responsible for the decisions you make while using the app.",
    p6: "This app makes frequent location requests, which require a lot of battery.  Quit the app while not in use to preserve battery.",
    privacyPolicy: "Privacy Policy",
    termsAndConditions: "Terms and Conditions",
    privacyPolicyPre: "By tapping 'Got it', you agree to the ",
    privacyPolicyPost: " and ",
    privacyURL: "https://dice-o.flycricket.io/privacy.html",
    termsAndConditionsURL: "https://dice-o.flycricket.io/terms.html",
    termsAndConditionsPost: ".",
    CTA: "Got it",
  },
  courseType: {
    standardDescription:"Visit every control in order",
    standardCTA:"Standard",
    scoreODescription:"Visit as many controls as you like in any order",
    scoreOCTA:"Score-O",
    importQRDescription:"Scan a QR code for a course someone has already made using Dice-O",
    importQRCTA:"Import Via QR",
  },
  permissions: {
    loading: "Loading...",
    loading2: "Either Dice-O is still trying to detect your GPS signal (in which case moving around/going outside may help if you are inside), or Dice-O can't access your GPS signal because you haven't yet granted Foreground Location permissions to the app.  To enable Foreground Location permissions, open your device's Settings app, search for Dice-O, and enable location permissions for the app.",
    noCamera: "No access to camera",
    noLocation: "",
    requestingCamera: "Requesting camera permissions",

  },
  continue: "Continue",
  ok: "Ok",
  boundary: {
    clearAll: "Clear all",
    moreBoundaryPointsAlertTitle: "Add More Boundary Points",
    moreBoundaryPointsAlertText: "Before continuing, your course boundary must contain at least three points.",
  },
  context: {
    start:'Start',
    finish:'Finish',
    notFound:"Not Found",
    skipped:"Skipped",
    found:"Found",
  },
  controlLogged: {
    seeResults: "See Results",
  },
  share: {
    share:'Share',
    part1:'I just finished a ',
    standard: 'standard ',
    scoreO: 'Score-O ',
    part2:'orienteering course with Dice-O and went ',
    part3:'!',
    TODO:'Add a part 2 and count the number of found controls',
    zeroDistance:'Check out the Dice-O Random Orienteering App!',
  },
  results:{
    control:'Control', 
    absoluteTime:'Clock', 
    elapsedTime:'Elapsed Time', 
    legTime:'Leg Time',
    distancePart1:'Distance (',
    distancePart2:')',
    done:'Done',
    status:'Status',
    totals:'Totals',
    pace:'Pace',
    na:"n/a",
    youDidIt:"You did it!",
    tabLabelData: "Data",
    tabLabelRoute: "Route",
  }
}