export const strings = {
  explainer: {
    addMarkerTool: "While using this tool, tap the map to add a new boundary marker at that location. New markers will be added along the red boundary.",
    boundaryMarker: "Press and hold the icons to move the boundary markers.",
    boundaryTool: "While using this tool, tap a boundary edge to activate it. New boundary markers will be added along the active edge (shown in red).",
    changeUnits: "Tap the course length to change units.",
    controlActive:"The next control to visit is in red.",
    controlFinish:"After visiting all numbered controls, go to the double-circle to finish!",
    controlRegular:"Travel to the numbered controls in order.",
    controlStart: "Travel to the triangle to start.",
    controlVisited: "Visited controls will turn grey.",
    deleteTool: "While using this tool, tap a marker to remove it.",
    gpsHint:"The GPS hint tool toggles whether your location is shown on the map.",
    layer: "Tap the layer icon to toggle between satellite, hybrid, terrain, map, and orienteering views.",
    moveControl: "Press and hold a circle to move a control.",
    moveFinish: "Press and hold the double circle to move the finish.",
    moveStart: "Press and hold the triangle to move the start.",
    QRIcon: "Tap to share the course with another person via QR code.  They will need to tap 'Import Course Via QR' from the Settings page.",
    randomTool: "Tap the die to roll a random orienteering course.",
    skip:"The skip tool lets you skip the next control.",
  },
  header: {
    back: "Back",
    courseType: "Course Type",
    disclaimer: "Disclaimer",
    exportQR: 'Share this Course',
    controlLogged: "Control Logged", //TODO differentiate between skipped and found controls
    game: 'Event in Progress',
    gameExit: 'Exit',
    gameExplainer: 'Completing a Course',
    gameSettings: "Settings",
    home: "Home",
    importQR: 'Import a Course',
    results: "Results",
    setBoundary: "Set Course Boundary",
    setBoundaryExplainer: 'Setting the Boundary',
    setBoundaryShort: "Boundary",
    setCourse: "Set the Course",
    setCourseExplainer: 'Setting the Course',
    setFinish: 'Tap to move the Finish',
    setFinishExplainer: 'Setting the Finish',
    setFinishShort: 'Finish',
    setStart: 'Tap to move the Start',
    setStartExplainer: 'Setting the Start',
    setStartShort: 'Start',
    settings: "Settings",
    settingsShort: "Settings",
  },
  disclaimer: {
    p1: "This app randomly generates orienteering-like courses.  It is not a replacement for orienteering courses set by orienteering professionals, which are very complex to set well.",
    p2: "When using this app, please use common sense.  Randomly placed controls may be in the middle of bodies of water, on private property, in a busy road, on train tracks, etc.  Before embarking on any course, review the location of every control, and adjust any that are inacessible or inappropriate.  Do not trespass while using this app.  Do not do anything potentially dangerous while using this app.  The creator of this app is in no way responsible for decisions you make while using the app.",
    p3: "Map data in the app is sourced from Google Maps, and is not nearly as detailed as good orienteering maps. This app is best used in an area that you already know well, or in conjunction with a real orienteering map.",
    p4: "This app makes frequent location requests, which require a lot of battery.  Quit the app while not in use to preserve battery.",
    privacyPolicy: "Privacy Policy",
    termsAndConditions: "Terms and Conditions",
    privacyPolicyPre: "By tapping 'Got it', you agree to the ",
    privacyPolicyPost: " and ",
    termsAndConditionsPost: ".",
    CTA: "Got it",
  },
  permissions: {
    loading: "Loading...",
    loading2: "If you haven't yet granted Location permissions to Dice-O, open Settings for this app and do so now.",
    noCamera: "No access to camera",
    noLocation: "",
    requestingCamera: "Requesting camera permissions",

  },
  continue: "Continue",
  ok: "Ok",
  boundary: {
    clearAll: "Clear all",
    moreBoundaryPointsAlertTitle: "Add More Boundary Points",
    moreBoundaryPointsAlertText: "Before continuing, your course boundary must contain at least three points.",
  },
  context: {
    start:'Start',
    finish:'Finish',
    notFound:"Not Found",
    skipped:"Skipped",
    found:"Found",
  },
  controlLogged: {
    seeResults: "See Results",
  },
  share: {
    standardPart1:'I just completed an orienteering course that was ',
    standardPart2:' kilometers with Dice-O!',
    scoreOPart1:'I just completed a Score-O orienteering course using the app Dice-O!',
    TODO:'Add a part 2 and count the number of found controls'
  },
  results:{
    control:'Control', 
    absoluteTime:'Absolute Time', 
    elapsedTime:'Elapsed Time', 
    legTime:'Leg Time',
    distancePart1:'Dist. (',
    distancePart2:')',
    done:'Done',
    status:'Status',
    pace:'Pace',
    na:"n/a",
    youDidIt:"You did it!",
  }
}